const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{PlanoDeFundoEmBlocos2: 0},
	{Sólido: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Fixar: 0},
	{animaçao: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{jogador: 0},
	{Teclado: 0},
	{Sprite: 0},
	{Senóide: 0},
	{Sprite2: 0},
	{Âncora: 0},
	{pontuaçao: 0},
	{açao: 0},
	{inimigo1: 0},
	{marcador: 0},
	{Sprite3: 0},
	{espinhos: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Texto: 0},
	{Áudio: 0},
	{Sprite6: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{ação: 0},
	{inimigo2: 0},
	{Sprite7: 0},
	{tela_menu: 0},
	{Mouse: 0},
	{Iniciar: 0},
	{sair: 0},
	{gameOver: 0},
	{tentar_novamente: 0},
	{voltar_menu: 0},
	{voltar_menu2: 0},
	{jogar_novamente: 0},
	{pontos: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	animaçao: class extends self.ISpriteInstance {},
	jogador: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	pontuaçao: class extends self.ITextInstance {},
	inimigo1: class extends self.ISpriteInstance {},
	marcador: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	espinhos: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	inimigo2: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	tela_menu: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Iniciar: class extends self.IButtonInstance {},
	sair: class extends self.IButtonInstance {},
	gameOver: class extends self.ISpriteInstance {},
	tentar_novamente: class extends self.IButtonInstance {},
	voltar_menu: class extends self.IButtonInstance {},
	voltar_menu2: class extends self.IButtonInstance {},
	jogar_novamente: class extends self.IButtonInstance {}
}